/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wildrune_ouyaframework_util_BufferUtils */

#ifndef _Included_wildrune_ouyaframework_util_BufferUtils
#define _Included_wildrune_ouyaframework_util_BufferUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wildrune_ouyaframework_util_BufferUtils
 * Method:    CopyJNI
 * Signature: ([FILjava/nio/Buffer;II)V
 */
JNIEXPORT void JNICALL Java_wildrune_ouyaframework_util_BufferUtils_CopyJNI
  (JNIEnv *, jclass, jfloatArray, jint, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
