/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wildrune_ouyaframework_graphics_utils_BufferUtils */

#ifndef _Included_wildrune_ouyaframework_graphics_utils_BufferUtils
#define _Included_wildrune_ouyaframework_graphics_utils_BufferUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wildrune_ouyaframework_graphics_utils_BufferUtils
 * Method:    CopyJNI
 * Signature: ([FILjava/nio/Buffer;II)V
 */
JNIEXPORT void JNICALL Java_wildrune_ouyaframework_graphics_utils_BufferUtils_CopyJNI___3FILjava_nio_Buffer_2II
  (JNIEnv *, jclass, jfloatArray, jint, jobject, jint, jint);

/*
 * Class:     wildrune_ouyaframework_graphics_utils_BufferUtils
 * Method:    CopyJNI
 * Signature: ([SILjava/nio/Buffer;II)V
 */
JNIEXPORT void JNICALL Java_wildrune_ouyaframework_graphics_utils_BufferUtils_CopyJNI___3SILjava_nio_Buffer_2II
  (JNIEnv *, jclass, jshortArray, jint, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
